version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 20
    target-branch: dev/2.0.0

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 20
    target-branch: dev/2.0.0
