name: PrivateServerSystem
version: '1.1.0'
author: derklaro
main: com.github.derklaro.privateservers.PrivateServersSpigot
description: An infinitely expandable private server system by derklaro
website: https://github.com/derklaro/ps-system

softdepend:
  - ProtocolLib
  - CloudNetAPI

commands:
  whitelist:
    description: Manage the whitelist of your private server
  visibility:
    description: Changes the visibility of the current server, public servers are shown in the server list
  removenpc:
    description: Set you in the mode that you are allowed to remove npcs
    aliases:
      - rmnpc
  createnpc:
    description: Create a new private server system npc
    aliases:
      - cnpc
