name: PrivateServerSystem
version: '1.1.0'
author: derklaro
main: com.github.derklaro.privateservers.PrivateServersSpigot
description: A private server system with cloud as module support
website: https://github.com/derklaro/ps-system

softdepend:
  - CloudNetAPI
  - ReformCloud2SpigotExecutor

commands:
  whitelist:
    description: Manage the whitelist of your private server
  removenpc:
    description: Set you in the mode that you are allowed to remove npcs
    permission: ps.command.rmnpc
    aliases:
      - rmnpc
  createnpc:
    description: Create a new private server system npc
    permission: ps.command.cnpc
    aliases:
      - cnpc