name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew
      - name: Prepare ZIP
        run: |
          mkdir -p temp/;
          cp license.txt temp/license.txt;
          cp ps-plugin-spigot/build/libs/ps-plugin-spigot.jar temp/plugin-spigot.jar

          mkdir temp/dev;
          cp */target/*-javadoc.jar temp/dev;
          cp ps-api/build/libs/ps-api.jar temp/dev/api.jar

          mkdir temp/modules;
          cp ps-cloudnet2/build/libs/ps-cloudnet2.jar temp/modules/cloudnet2.jar;
          cp ps-cloudnet2-legacy/build/libs/ps-cloudnet2-legacy.jar temp/modules/cloudnet2-legacy.jar;
          cp ps-cloudnet3/build/libs/ps-cloudnet3.jar temp/modules/cloudnet3.jar;
          cp ps-lobby-spigot/build/libs/ps-lobby-spigot.jar temp/modules/lobby-spigot.jar;
          cp ps-runner-spigot/build/libs/ps-runner-spigot.jar temp/modules/runner-spigot.jar;
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ps-system
          path: temp/
