name: Java CI

on:
  push:
    branches:
      - master
      - dev/1.1.0

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Build with Maven
        run: mvn -V clean package --file pom.xml
